<?php
    if(isset($_POST['tombol'])){
        $jalurPenerimaan = $_POST['jalurPenerimaan'];
        $namaMahasiswa = $_POST['namamahasiswa'];
        $ttlMahasiswa = $_POST['ttlmahasiswa'];
        $jenisKelamin = $_POST['jenisKelamin'];
        $agama = $_POST['agama'];
        $status = $_POST['status'];
        $alamat = $_POST['alamat'];
        $kodePos = $_POST['kodePos'];
        $noHP = $_POST['noHP'];
        $email = $_POST['email'];
        $asalSekolah = $_POST['asalSekolah'];
        $tahunLulus = $_POST['tahunLulus'];
        $namaAyah = $_POST['namaAyah'];
        $namaIbu = $_POST['namaIbu'];
        $alamatOrtu = $_POST['alamatOrtu'];
        $kodePosOrtu = $_POST['kodePosOrtu'];
        $noHPOrtu = $_POST['noHPOrtu'];
        $pendidikanAyah = $_POST['pendidikanAyah'];
        $pendidikanIbu = $_POST['pendidikanIbu'];
        $statusAyah = $_POST['statusAyah'];
        $statusIbu = $_POST['statusIbu'];
        $pekerjaanAyah = $_POST['pekerjaanAyah'];
        $pekerjaanIbu = $_POST['pekerjaanIbu'];
        $programStudi1 = $_POST['programStudi1'];
        $programStudi2 = $_POST['programStudi2'];
        $sumberInformasi = $_POST['sumberInformasi'];
        $gelombang = $_POST['gelombang'];
        echo "Jalur Penerimaan          = ".$jalurPenerimaan;
        echo "<br>Nama Mahasiswa            = ".$namaMahasiswa;
        echo "<br>Tempat/Tanggal Lahir      = ".$ttlMahasiswa;
        echo "<br>Jenis Kelamin             = ".$jenisKelamin;
        echo "<br>Agama                     = ".$agama;
        echo "<br>Status                    = ".$status;
        echo "<br>Alamat                    = ".$alamat;
        echo "<br>Kode Pos                  = ".$kodePos;
        echo "<br>nomor HP                  = ".$noHP;
        echo "<br>Email                     = ".$email;
        echo "<br><br>DATA ASAL SEKOLAH CALON MAHASISWA";
        echo "<br>Asal Sekolah              = ".$asalSekolah;
        echo "<br>Tahun Lulus               = ".$tahunLulus;
        echo "<br><br>DATA ORANG TUA CALON MAHASISWA";
        echo "<br>Nama Ayah                 = ".$namaAyah;
        echo "<br>Nama Ibu                  = ".$namaIbu;
        echo "<br>Alamat                    = ".$alamatOrtu;
        echo "<br>Kode Pos                  = ".$kodePosOrtu;
        echo "<br>Nomor HP                  = ".$noHPOrtu;
        echo "<br>Pendidikan Terakhir Ayah  = ".$pendidikanAyah;
        echo "<br>Pendidikan Terakhir Ibu   = ".$pendidikanIbu;
        echo "<br>Status Ayah               = ".$statusAyah;
        echo "<br>Status Ibu                = ".$statusIbu;
        echo "<br>Pekerjaan Ayah            = ".$pekerjaanAyah;
        echo "<br>Pekerjaan Ibu             = ".$pekerjaanIbu;
        echo "<br><br>PEMINATAN PROGRAM STUDI";
        echo "<br>Pilihan Program Studi 1   = ".$programStudi1;
        echo "<br>Pilihan Program Studi 2   = ".$programStudi2;
        echo "<br>Sumber Informasi          = ".$sumberInformasi;
        echo "<br><br>Ujian Saringan Masuk";
        echo "<br>Pilihan Gelombang          = ".$gelombang;
    }
?>